name = "qri"
# hashicorp/go-getter URLs, so in the future we can support fetching test plans
# from GitHub.
source_path = "file://${TESTGROUND_SRCDIR}/plans/qri"

[defaults]
builder = "exec:go"
runner = "local:exec"

[builders."docker:go"]
enabled = true
go_version = "1.13"
module_path = "github.com/qri-io/testground-qri"
exec_pkg = "."
go_ipfs_version = "0.4.21"

[builders."exec:go"]
enabled = true
module_path = "github.com/qri-io/testground-qri"
exec_pkg = "."

[runners."local:docker"]
enabled = true

[runners."local:exec"]
enabled = true

[runners."cluster:swarm"]
enabled = true

[[testcases]]
name = "remote-push"
instances = { min = 2, max = 200, default = 3 }

  [testcases.params]
  timeout_secs = { type = "int", desc = "test timeout", unit = "seconds", default = 300 }
  latency      = { type = "int", desc = "latency between peers", unit = "ms", default = 100 }